# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bloomIOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bloomIOS

  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'MessageUI'

  target 'bloomIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'bloomIOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
